=== Bernardo-MG/RPG-Toolbox-Pendragon-Core/src/test/resources/parameter/value_mirror.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="test_data">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="data" type="value" />
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="uniqueData">
			<xs:selector xpath="data" />
			<xs:field xpath="value" />
		</xs:unique>
	</xs:element>

	<xs:complexType name="value">
		<xs:sequence>
			<xs:element name="value" type="xs:integer" />
			<xs:element name="mirror" type="xs:integer" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== Bernardo-MG/RPG-Toolbox-Pendragon-Core/src/test/resources/parameter/value_mirror.xml
<?xml version="1.0" encoding="UTF-8"?>
<test_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="value_mirror.xsd">
	<data>
		<value>1</value>
		<mirror>19</mirror>
	</data>
	<data>
		<value>10</value>
		<mirror>10</mirror>
	</data>
	<data>
		<value>19</value>
		<mirror>1</mirror>
	</data>
	<data>
		<value>20</value>
		<mirror>0</mirror>
	</data>
	<data>
		<value>21</value>
		<mirror>0</mirror>
	</data>
	<data>
		<value>25</value>
		<mirror>0</mirror>
	</data>
	<data>
		<value>30</value>
		<mirror>0</mirror>
	</data>
</test_data>
